insert into author (name) values ('Drucie Goodbourn');
insert into books (title, priceOld, price, author_id) values ('exploit real-time e-commerce', '$203.23', '$43.37', (select id from author where name = 'Drucie Goodbourn'));
insert into author (name) values ('Marcia Aggiss');
insert into books (title, priceOld, price, author_id) values ('utilize real-time interfaces', '$260.31', '$35.96', (select id from author where name = 'Marcia Aggiss'));
insert into author (name) values ('Giovanni Bigg');
insert into books (title, priceOld, price, author_id) values ('extend strategic e-services', '$272.00', '$151.04', (select id from author where name = 'Giovanni Bigg'));
insert into author (name) values ('Duffie Eynon');
insert into books (title, priceOld, price, author_id) values ('iterate integrated solutions', '$271.58', '$141.40', (select id from author where name = 'Duffie Eynon'));
insert into author (name) values ('Anselma McKennan');
insert into books (title, priceOld, price, author_id) values ('cultivate magnetic e-commerce', '$278.43', '$54.44', (select id from author where name = 'Anselma McKennan'));
insert into author (name) values ('Gert Kira');
insert into books (title, priceOld, price, author_id) values ('architect vertical ROI', '$282.54', '$102.61', (select id from author where name = 'Gert Kira'));
insert into author (name) values ('Clerc Djakovic');
insert into books (title, priceOld, price, author_id) values ('disintermediate extensible architectures', '$295.38', '$181.27', (select id from author where name = 'Clerc Djakovic'));
insert into author (name) values ('Stacee Elsy');
insert into books (title, priceOld, price, author_id) values ('extend leading-edge methodologies', '$283.08', '$97.96', (select id from author where name = 'Stacee Elsy'));
insert into author (name) values ('Dorotea Bonhill');
insert into books (title, priceOld, price, author_id) values ('integrate one-to-one systems', '$258.51', '$52.25', (select id from author where name = 'Dorotea Bonhill'));
insert into author (name) values ('Minni Bunney');
insert into books (title, priceOld, price, author_id) values ('revolutionize 24/7 infrastructures', '$260.79', '$33.69', (select id from author where name = 'Minni Bunney'));
insert into author (name) values ('Berty Gandley');
insert into books (title, priceOld, price, author_id) values ('enhance innovative e-services', '$256.54', '$160.98', (select id from author where name = 'Berty Gandley'));
insert into author (name) values ('Raynard Tesdale');
insert into books (title, priceOld, price, author_id) values ('maximize 24/365 e-tailers', '$262.07', '$34.06', (select id from author where name = 'Raynard Tesdale'));
insert into author (name) values ('Joanna Hutfield');
insert into books (title, priceOld, price, author_id) values ('scale integrated architectures', '$257.66', '$32.97', (select id from author where name = 'Joanna Hutfield'));
insert into author (name) values ('Dannie Glidder');
insert into books (title, priceOld, price, author_id) values ('e-enable frictionless web services', '$288.19', '$90.52', (select id from author where name = 'Dannie Glidder'));
insert into author (name) values ('Timmie Adshede');
insert into books (title, priceOld, price, author_id) values ('strategize B2B channels', '$232.27', '$44.83', (select id from author where name = 'Timmie Adshede'));
insert into author (name) values ('Fernando Neads');
insert into books (title, priceOld, price, author_id) values ('syndicate compelling deliverables', '$287.45', '$101.89', (select id from author where name = 'Fernando Neads'));
insert into author (name) values ('Teddy Guilliland');
insert into books (title, priceOld, price, author_id) values ('utilize bleeding-edge users', '$281.37', '$146.21', (select id from author where name = 'Teddy Guilliland'));
insert into author (name) values ('Paloma Grebert');
insert into books (title, priceOld, price, author_id) values ('cultivate 24/365 networks', '$270.99', '$184.76', (select id from author where name = 'Paloma Grebert'));
insert into author (name) values ('Kristos Usher');
insert into books (title, priceOld, price, author_id) values ('embrace plug-and-play platforms', '$278.36', '$77.71', (select id from author where name = 'Kristos Usher'));
insert into author (name) values ('Darcey Rohmer');
insert into books (title, priceOld, price, author_id) values ('target innovative paradigms', '$298.94', '$130.01', (select id from author where name = 'Darcey Rohmer'));
insert into author (name) values ('Cristie Isacsson');
insert into books (title, priceOld, price, author_id) values ('generate open-source e-business', '$276.57', '$113.25', (select id from author where name = 'Cristie Isacsson'));
insert into author (name) values ('Lindsay Coutthart');
insert into books (title, priceOld, price, author_id) values ('implement user-centric e-markets', '$254.70', '$115.31', (select id from author where name = 'Lindsay Coutthart'));
insert into author (name) values ('Helyn Schneidar');
insert into books (title, priceOld, price, author_id) values ('utilize magnetic supply-chains', '$279.70', '$77.86', (select id from author where name = 'Helyn Schneidar'));
insert into author (name) values ('Bette-ann Askem');
insert into books (title, priceOld, price, author_id) values ('e-enable dot-com supply-chains', '$297.83', '$110.15', (select id from author where name = 'Bette-ann Askem'));
insert into author (name) values ('Dom Robuchon');
insert into books (title, priceOld, price, author_id) values ('facilitate efficient eyeballs', '$232.30', '$131.48', (select id from author where name = 'Dom Robuchon'));
